version = 1

test_patterns = [
  "tests/"
]

exclude_patterns = [
  "beacon/beacon_pb2.py",
  "beacon/beacon_pb2_grpc.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  max_line_length = 90
  skip_doc_coverage = ["module", "magic", "class"]

[[analyzers]]
name = "test-coverage"
enabled = true
