# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beacon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='beacon.proto',
  package='beacon',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x62\x65\x61\x63on.proto\x12\x06\x62\x65\x61\x63on\"\x07\n\x05\x45mpty\"\x85\x01\n\x0b\x41uthRequest\x12\x16\n\x0e\x62\x65\x61\x63on_api_key\x18\x01 \x01(\t\x12\x15\n\rrepository_id\x18\x02 \x01(\x03\x12\x1d\n\x15\x62\x65\x61\x63on_client_version\x18\x03 \x01(\t\x12\x16\n\x0esource_version\x18\x04 \x01(\t\x12\x10\n\x08hostname\x18\x05 \x01(\t\"!\n\x0c\x41uthResponse\x12\x11\n\tstream_id\x18\x01 \x01(\t\";\n\x05\x45vent\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\x03\x12\r\n\x05\x63ount\x18\x03 \x01(\x03\"\x8a\x01\n\x05\x42\x61tch\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12&\n\nevent_type\x18\x02 \x01(\x0e\x32\x12.beacon.Batch.Type\x12\x1d\n\x06\x65vents\x18\x03 \x03(\x0b\x32\r.beacon.Event\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x14\n\x04Type\x12\x05\n\x01\x66\x10\x00\x12\x05\n\x01\x65\x10\x01\x32u\n\x06\x42\x65\x61\x63on\x12?\n\x10InitializeStream\x12\x13.beacon.AuthRequest\x1a\x14.beacon.AuthResponse\"\x00\x12*\n\x08Transmit\x12\r.beacon.Batch\x1a\r.beacon.Empty\"\x00\x62\x06proto3')
)



_BATCH_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='beacon.Batch.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='f', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='e', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=384,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_BATCH_TYPE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='beacon.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=31,
)


_AUTHREQUEST = _descriptor.Descriptor(
  name='AuthRequest',
  full_name='beacon.AuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beacon_api_key', full_name='beacon.AuthRequest.beacon_api_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repository_id', full_name='beacon.AuthRequest.repository_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beacon_client_version', full_name='beacon.AuthRequest.beacon_client_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_version', full_name='beacon.AuthRequest.source_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='beacon.AuthRequest.hostname', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=167,
)


_AUTHRESPONSE = _descriptor.Descriptor(
  name='AuthResponse',
  full_name='beacon.AuthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='beacon.AuthResponse.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=202,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='beacon.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='beacon.Event.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='beacon.Event.location', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='beacon.Event.count', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=263,
)


_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='beacon.Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='beacon.Batch.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='beacon.Batch.event_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='beacon.Batch.events', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='beacon.Batch.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BATCH_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=404,
)

_BATCH.fields_by_name['event_type'].enum_type = _BATCH_TYPE
_BATCH.fields_by_name['events'].message_type = _EVENT
_BATCH_TYPE.containing_type = _BATCH
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AuthRequest'] = _AUTHREQUEST
DESCRIPTOR.message_types_by_name['AuthResponse'] = _AUTHRESPONSE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'beacon_pb2'
  # @@protoc_insertion_point(class_scope:beacon.Empty)
  ))
_sym_db.RegisterMessage(Empty)

AuthRequest = _reflection.GeneratedProtocolMessageType('AuthRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHREQUEST,
  __module__ = 'beacon_pb2'
  # @@protoc_insertion_point(class_scope:beacon.AuthRequest)
  ))
_sym_db.RegisterMessage(AuthRequest)

AuthResponse = _reflection.GeneratedProtocolMessageType('AuthResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHRESPONSE,
  __module__ = 'beacon_pb2'
  # @@protoc_insertion_point(class_scope:beacon.AuthResponse)
  ))
_sym_db.RegisterMessage(AuthResponse)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'beacon_pb2'
  # @@protoc_insertion_point(class_scope:beacon.Event)
  ))
_sym_db.RegisterMessage(Event)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), dict(
  DESCRIPTOR = _BATCH,
  __module__ = 'beacon_pb2'
  # @@protoc_insertion_point(class_scope:beacon.Batch)
  ))
_sym_db.RegisterMessage(Batch)



_BEACON = _descriptor.ServiceDescriptor(
  name='Beacon',
  full_name='beacon.Beacon',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=406,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitializeStream',
    full_name='beacon.Beacon.InitializeStream',
    index=0,
    containing_service=None,
    input_type=_AUTHREQUEST,
    output_type=_AUTHRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Transmit',
    full_name='beacon.Beacon.Transmit',
    index=1,
    containing_service=None,
    input_type=_BATCH,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BEACON)

DESCRIPTOR.services_by_name['Beacon'] = _BEACON

# @@protoc_insertion_point(module_scope)
