version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox

    working_directory: ~/repo

    steps:
      - checkout
      - run: tox
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
